# -*- coding: utf-8 -*-
"""NLPproject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1bkj-Bc49KShGBtz5z6q3J0p02wu6OjuS
"""

# STEP 1 ;
import zipfile
import pandas as pd

# STEP 2 ;
from google.colab import files
uploaded = files.upload()

# STEP 3 ;
for filename in uploaded.keys():
    if filename.endswith('.zip'):
        with zipfile.ZipFile(filename, 'r') as zip_ref:
            zip_ref.extractall('./data')  # extract to folder called 'data'
        print("✅ Extracted files to ./data")

# STEP 4 ;
import os

for f in os.listdir('./data'):
    if f.endswith('.csv'):
        csv_path = os.path.join('./data', f)
        print("Found CSV:", csv_path)
        try:
            df = pd.read_csv(csv_path, encoding='utf-8')
        except UnicodeDecodeError:
            df = pd.read_csv(csv_path, encoding='latin1')
        break

# STEP 5 ;
print("📊 Dataset shape:", df.shape)
df.head()