# -*- coding: utf-8 -*-
"""Untitled23.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/179T0HrjRymjAYUfSiY9NL7-PWt-B1s-S
"""

from google.colab import files
import pandas as pd
import zipfile
import os

# Choose file from your computer
uploaded = files.upload()

# Get uploaded file name
filename = list(uploaded.keys())[0]

print("Uploaded File:", filename)

# If ZIP file
if filename.endswith(".zip"):
    with zipfile.ZipFile(filename, "r") as zip_ref:
        zip_ref.extractall()

    print("\nFiles inside ZIP:")
    print(os.listdir())

# If CSV file
elif filename.endswith(".csv"):
    df = pd.read_csv(filename)
    print("\nDataset Preview:")
    print(df.head())

# If Excel file
elif filename.endswith(".xlsx"):
    df = pd.read_excel(filename)
    print("\nDataset Preview:")
    print(df.head())

else:
    print("Unsupported file format!")

print(df.columns)

df.info()

df.describe()

df.isnull().sum()

df.groupby("Item Type")["Sales"].sum(3)

df.groupby("Item Type").sum()